# Python Numpy functions

## Code 1

In [2]:
## Print the given array in reverse order
import numpy as np

def arrays(arr):
    return(np.array(arr[::-1], float))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Code 2

In [3]:
## Reshape the given array into 3*3 Matrix

import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Code 3

In [4]:
## finding the transpose and Flatten in the given matrix

import numpy as np

n,m = map(int,input().split())
array = np.array([input().strip().split() for _ in range(n)],int)

print(array.transpose())
print(array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Code 4

In [5]:
## Concatenating the two arrays
import numpy as np

a,b,c = map(int,input().split())
arr_A = np.array([input().strip().split() for _ in range(a)],int)
arr_B = np.array([input().strip().split() for _ in range(b)],int)

print(np.concatenate((arr_A,arr_B),axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Code 5 

In [ ]:
# Finding the zeros and ones 

import numpy as np

nums = tuple(map(int,input().split()))

print(np.zeros(nums, dtype = np.int))
print(np.ones(nums,dtype = np.int))

## Code 6

In [2]:
## Printing the eye and identity matrix

import numpy as np
n,m = map(int,input().split())
np.set_printoptions(legacy = '1.13')
print(np.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Code 7

In [3]:
import numpy as np

n,m = map(int,input().split())
A = np.array([list(map(int,input().split())) for _ in range(n)],int)
B = np.array([list(map(int,input().split())) for _ in range(n)],int)
print(np.add(A,B),np.subtract(A,B),np.multiply(A,B),np.floor_divide(A,B)
      ,np.mod(A,B),np.power(A,B),sep='\n')

1 4
2 4 6 8
3 5 7 9
[[ 5  9 13 17]]
[[-1 -1 -1 -1]]
[[ 6 20 42 72]]
[[0 0 0 0]]
[[2 4 6 8]]
[[        8      1024    279936 134217728]]


## Code 8 

In [4]:
## Print Floor,Ceil,rint from a array

import numpy as np
np.set_printoptions(legacy = '1.13')
l = list(map(float,input().split()))
arr = np.array(l)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Code 9 

In [5]:
## find the sum and prod of given value

import numpy as np

n,m = map(int,input().split())
A = np.array([input().split() for _ in range(n)],int)
print(np.prod(np.sum(A,axis=0),axis=0))

2 2
1 2
3 4
24


## Code 10

In [6]:
## finding the max and min value 

import numpy as np

n,m = map(int,input().split())
list1 = []
for i in range(n):
    l =list(map(int,input().split()))
    list1.append(l)
arr = np.array(list1)
print(np.max(np.min(arr,axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


## Code 11 

In [1]:
## Finding the mean,var and std of the given array

import numpy as np 

n,m = map(int, input().split())
b = []
for i in range(n):
    a = list(map(int, input().split()))
    b.append(a)

b = np.array(b)

#np.set_printoptions(legacy='1.13')
print(np.mean(b, axis = 1))
print(np.var(b, axis = 0))
output = np.std(b)
print(output.round(12))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


## Code 12 

In [2]:
## Finding the dot product of given array
import numpy as np

n = int(input())
A = np.array([input().split() for i in range(n)],int)
B = np.array([input().split() for i in range(n)],int)
print(A.dot(B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Code 13 

In [4]:
## finding the inner and outer 
import numpy as np
a = np.array(input().split(),int)
b = np.array(input().split(),int)
print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


## Code 14

In [5]:
## finding the polynomial factor

import numpy as np

l = list(map(float,input().split()))
x = int(input())
arr = np.array(l)
print(np.polyval(arr,x))

1.1 2 3
0
3.0


## Code 15 

In [6]:
## finding the linear algebra 
import numpy as np

n = int(input())
arr = np.array([input().split() for i in range(n)],dtype=float)
deterval = np.linalg.det(arr)
print(deterval.round(2))

2
1.1 1.1
1.1 1.1
0.0
